apiVersion: apps/v1
kind: Deployment
metadata:
  name: programmer-server-deployment
  labels:
    deploy: programmer-server-deployment-label
spec:
  replicas: 3
  selector:
    matchLabels:
      webapp: programmer-server-pod-label
  template:
    metadata:
      labels:
        webapp: programmer-server-pod-label
    spec:
      containers:
      - name: programmer-server-container
        image: harisheoran/programmer-server:main
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
        - name: MONGO_IP
          value: "cluster0.9vrhkmz.mongodb.net"
        - name: MONGO_APP
          value: "Cluster0"
        - name: MONGO_USER
          value: "harisheoran"
        - name: MONGO_PASSWORD
          value: "harish2k24"
        - name: SESSION_SECRET
          value: "mysecret123"
---
apiVersion: v1
kind: Service
metadata:
  name: programmer-server-service
spec:
  type: NodePort
  selector:
    webapp: programmer-server-pod-label
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-ingress-class
  rules:
  - http:
      paths:
      - path: /myserver
        pathType: Prefix
        backend:
          service:
            name: programmer-server-service
            port:
              number: 80
