pipeline{
    agent any
    environment{
                DOCKERHUB_CREDENTIALS = credentials('docker')
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    stages{
        stage('Build'){
            steps{
                sh 'docker-compose -f docker-compose.yml -f docker-compose.prod.yml build'
            }
        }
        stage('Login to Docker Hub'){
           
            steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('push'){
            steps{
                sh 'docker-compose -f docker-compose.yml -f docker-compose.prod.yml push'
            }
        }
    }
    post {
    always {
        script {
            sh 'docker logout'
            emailext subject: "Pipeline Status: ${BUILD_NUMBER}",
                      body: '''<html>
                                <body>
                                    <p>Build Status: ${BUILD_STATUS} and Build URL: ${BUILD_URL}</p>
                                </body>
                             </html>''',
                      to: 'harishdev1010@gmail.com',
                      from: 'programmerserver@mail.com',
                      replyTo: 'programmerserver@mail.com',
                      mimeType: 'text/html'
        }
    }
    }
}