pipeline{
    agent any
    environments{
                DOCKERHUB_CREDENTIALS = credentials('docker')
            }
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    stages{
        stage('Build'){
            steps{
                sh 'docker-compose -f docker-compose.yml -f docker-compose.prod.yml build'
            }
        }
        stage('Login to Docker Hub'){
           
            steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('push'){
            sh 'docker-compose -f docker-compose.yml -f docker-compose.prod.yml push'
        }
    }
    post {
        always {
            sh 'docker logout'
    }
  }
}